//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountCreation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRequest
    {
        public int Id { get; set; }
        public string Edipi { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string Mi { get; set; }
        public string Email { get; set; }
        public string Rank { get; set; }
        public string Org { get; set; }
        public string Department { get; set; }
        public string Installation { get; set; }
        public string Branch { get; set; }
        public string Bldg { get; set; }
        public string Room { get; set; }
        public string Office { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string Persona { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string SamAccountName { get; set; }
        public string HomeFolder { get; set; }
        public Nullable<byte> NiprReg { get; set; }
        public Nullable<byte> NiprSa { get; set; }
        public Nullable<byte> NiprEp { get; set; }
        public Nullable<byte> Vpn { get; set; }
        public Nullable<byte> Sipr { get; set; }
        public Nullable<byte> SupSigned { get; set; }
        public Nullable<byte> SecSigned { get; set; }
        public string SupEdipi { get; set; }
        public Nullable<System.DateTime> SupDateSigned { get; set; }
        public string SecEdipi { get; set; }
        public Nullable<System.DateTime> SecDateSigned { get; set; }
        public Nullable<byte> AcctStatus { get; set; }
    }
}
