//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountCreation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRequest
    {
        public int Id { get; set; }
        public string Edipi { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string Mi { get; set; }
        public string Email { get; set; }
        public string Rank { get; set; }
        public string Branch { get; set; }
        public string Macom { get; set; }
        public string Installation { get; set; }
        public string OrgUnit { get; set; }
        public string Bldg { get; set; }
        public string Room { get; set; }
        public string Office { get; set; }
        public string Phone { get; set; }
        public string Persona { get; set; }
        public string EpUnits { get; set; }
        public string Mos { get; set; }
        public string SamAccountName { get; set; }
        public string HomeFolder { get; set; }
        public Nullable<bool> Nipr { get; set; }
        public Nullable<bool> NiprSa { get; set; }
        public Nullable<bool> NiprEp { get; set; }
        public Nullable<bool> Vpn { get; set; }
        public Nullable<bool> Sipr { get; set; }
        public Nullable<bool> SupSigned { get; set; }
        public Nullable<bool> SecSigned { get; set; }
        public string SupEdipi { get; set; }
        public Nullable<System.DateTime> SupDateSigned { get; set; }
        public string SecEdipi { get; set; }
        public Nullable<System.DateTime> SecDateSigned { get; set; }
        public Nullable<bool> Training { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string RequestType { get; set; }
        public string AccountType { get; set; }
        public string SaEdipi { get; set; }
        public string SaName { get; set; }
        public string AcctStatus { get; set; }
    }
}
