//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountCreation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SettingEntities : DbContext
    {
        public SettingEntities()
            : base("name=SettingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Branch> Branches { get; set; }
        public DbSet<Persona> Personas { get; set; }
        public DbSet<Rank> Ranks { get; set; }
        public DbSet<UnitOrg> UnitOrgs { get; set; }
        public DbSet<Installation> Installations { get; set; }
        public DbSet<Office> Offices { get; set; }
    }
}
